# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [9]:
# import libraries
import pandas as pd
import numpy as np
import re

from sqlalchemy import create_engine
import pymysql;
from sqlalchemy import create_engine;

#### Import data set.

Import `pokemon_stats` table from database `Pokemon` from Ironhack's databases. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [10]:
# # import data set from Ironhack's database
# driver   = 'mysql+pymysql:'
# user     = 'data-guest_viewer'
# password = 'guest_ironhack'
# ip       = '34.65.10.136'
# database = 'pokemon'

In [11]:
# import data set from Ironhack's database
driver   = 'mysql+pymysql:'
user     = 'data-guest_viewer'
password = 'guest_ironhack'
ip       = '127.0.0.1'
database = 'pokemon'

In [12]:
# sqlEngine       = create_engine('mysql+pymysql://root:@127.0.0.1', pool_recycle=3600)

# dbConnection    = sqlEngine.connect()

# frame           = pd.read_sql("select * from test.uservitals", dbConnection);

 

# pd.set_option('display.expand_frame_repr', False)

# print(frame)

 

# dbConnection.close()

In [13]:
connection_string = f'{driver}//{user}:{password}@{ip}/{database}'
print(connection_string)

mysql+pymysql://data-guest_viewer:guest_ironhack@127.0.0.1/pokemon

In [14]:
engine = create_engine(connection_string)
print(engine)

Engine(mysql+pymysql://data-guest_viewer:***@127.0.0.1/pokemon)

In [15]:
pokemon_show = pd.read_sql('SHOW TABLES', engine)
pokemon_show

  Tables_in_pokemon
0     pokemon_stats

In [16]:
df_pokemon = pd.read_sql('SELECT * FROM pokemon_stats', engine)

df_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [17]:
df_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

#### Print first 10 rows of `pokemon`.

In [28]:
df_pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,,314,44,48,65,50,64,43,1,False,0.738462

In [19]:
df_pokemon['Name'].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoran‚ôÄ', 'Nidorina', 'Nidoqueen', 'Nidoran‚ôÇ',
       'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix',
       'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
       'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
       'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
       'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
       'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam',
       'AlakazamMega Alakazam', 'Machop', 'Machoke', 'Machamp',
       'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'Flab√©b√©', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Extract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [20]:
distinct_types = np.unique(df_pokemon[['Type 1', 'Type 2']])

type_1_unique =  df_pokemon['Type 1'].unique()
print('Type 1 unique values are : ', df_pokemon['Type 1'].unique())

print('----')
type_2_unique =  df_pokemon['Type 2'].unique()
print('Type 2 unique values are : ', df_pokemon['Type 2'].unique())
print('----')
print('Both columns unique values combined are : ')
distinct_types

Type 1 unique values are :  ['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying']
----
Type 2 unique values are :  ['Poison' '' 'Flying' 'Dragon' 'Ground' 'Fairy' 'Grass' 'Fighting'
 'Psychic' 'Steel' 'Ice' 'Rock' 'Dark' 'Water' 'Electric' 'Fire' 'Ghost'
 'Bug' 'Normal']
----
Both columns unique values combined are :

array(['', 'Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting',
       'Fire', 'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal',
       'Poison', 'Psychic', 'Rock', 'Steel', 'Water'], dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [21]:
# using lambda function to re.sub expression feat. Mega
df_pokemon['Name'] = df_pokemon['Name'].apply(lambda x: re.sub(r'\w+Mega','Mega', x))

# test transformed data
df_pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [22]:
df_pokemon['A/D Ratio'] = df_pokemon['Attack'] / df_pokemon['Defense']

df_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667

#### Identify the pokemon with the highest `A/D Ratio`.

In [23]:
#Number1 pokemon in A/D Ratio
df_pokemon.loc[df_pokemon[['A/D Ratio']].idxmax()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.0

In [24]:
#displaying top 10 best A/D Ratio
df_pokemon.sort_values(by='A/D Ratio', ascending=False).head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.000000
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500000
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000
453,408,Cranidos,Rock,,350,67,125,40,30,30,58,4,False,3.125000
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000000
428,386,DeoxysNormal Forme,Psychic,,600,50,150,50,150,50,150,3,True,3.000000
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False,3.000000
454,409,Rampardos,Rock,,495,97,165,60,65,50,58,4,False,2.750000
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667
186,172,Pichu,Electric,,205,20,40,15,35,35,60,2,False,2.666667

#### Identify the pokemon with the lowest A/D Ratio.

In [25]:
#lowest pokemon in A/D Ration
df_pokemon.loc[df_pokemon[['A/D Ratio']].idxmin()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

In [26]:
#displaying bottom 20 lowest A/D Ratio
df_pokemon.sort_values(by='A/D Ratio').head(20)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478
139,129,Magikarp,Water,,200,20,10,55,15,20,80,1,False,0.181818
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.279070
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.281250
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.285714
189,175,Togepi,Fairy,,245,35,20,65,40,65,20,2,False,0.307692
456,411,Bastiodon,Rock,Steel,495,60,52,168,47,138,30,4,False,0.309524
323,299,Nosepass,Rock,,375,30,45,135,45,90,30,3,False,0.333333
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False,0.333333
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False,0.333333
624,563,Cofagrigus,Ghost,,483,58,50,145,95,105,30,5,False,0.344828
623,562,Yamask,Ghost,,303,38,30,85,55,65,30,5,False,0.352941
455,410,Shieldon,Rock,Steel,350,30,42,118,42,88,30,4,False,0.355932
14,11,Metapod,Bug,,205,50,20,55,25,25,30,1,False,0.363636
733,665,Spewpa,Bug,,213,45,22,60,27,30,29,6,False,0.366667
528,476,Probopass,Rock,Steel,525,60,55,145,75,150,40,4,False,0.379310
508,458,Mantyke,Water,Flying,345,45,20,50,60,120,50,4,False,0.400000
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False,0.400000
149,138,Omanyte,Rock,Water,355,35,40,100,90,55,35,1,False,0.400000
87,80,Mega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False,0.416667

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [35]:
def combo_type_creator(row):
    if row['Type 2'] =='':
        return row['Type 1']
    else:
        return row['Type 1'] + ' - ' + row['Type 2']

In [37]:
df_pokemon['Combo Type'] = df_pokemon.apply(lambda row: combo_type_creator(row), axis=1)

df_pokemon.head(20)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass - Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass - Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass - Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass - Poison
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302,Fire
5,5,Charmeleon,Fire,,405,58,64,58,80,65,80,1,False,1.103448,Fire
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923,Fire - Flying
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171,Fire - Dragon
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333,Fire - Flying
9,7,Squirtle,Water,,314,44,48,65,50,64,43,1,False,0.738462,Water
10,8,Wartortle,Water,,405,59,63,80,65,80,58,1,False,0.787500,Water
11,9,Blastoise,Water,,530,79,83,100,85,105,78,1,False,0.830000,Water
12,9,Mega Blastoise,Water,,630,79,103,120,135,115,78,1,False,0.858333,Water
13,10,Caterpie,Bug,,195,45,30,35,20,20,45,1,False,0.857143,Bug
14,11,Metapod,Bug,,205,50,20,55,25,25,30,1,False,0.363636,Bug
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False,0.900000,Bug - Flying
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,1.166667,Bug - Poison
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,0.500000,Bug - Poison
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,2.250000,Bug - Poison
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000,Bug - Poison

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [40]:
#Top 5 A/D Ratio

df_pokemon.sort_values(by=['A/D Ratio'], ascending=False).head(5)

#2nd method
df_pokemon.nlargest(n=5, columns=['A/D Ratio'])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water - Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug - Poison
453,408,Cranidos,Rock,,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water - Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [64]:
#list comprehension calling for Combo Types in Top 5
top_5_types = [i for i in df_pokemon.nlargest(n=5, columns=['A/D Ratio'])['Combo Type']]

In [65]:
top_5_types

['Psychic', 'Water - Dark', 'Bug - Poison', 'Rock', 'Water - Dark']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [66]:
#creating sub_df with only Pokemons from Top 5 list
df_top_5_types = df_pokemon[df_pokemon['Combo Type'].isin(top_5_types)]

In [67]:
df_top_5_types

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,1.166667,Bug - Poison
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,0.500000,Bug - Poison
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,2.250000,Bug - Poison
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000,Bug - Poison
53,48,Venonat,Bug,Poison,305,60,55,50,40,55,45,1,False,1.100000,Bug - Poison
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,606,Beheeyem,Psychic,,485,75,75,75,125,95,40,5,False,1.000000,Psychic
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False,1.417910,Water - Dark
745,677,Espurr,Psychic,,355,62,48,54,63,60,68,6,False,0.888889,Psychic
746,678,MeowsticMale,Psychic,,466,74,48,76,83,81,104,6,False,0.631579,Psychic
747,678,MeowsticFemale,Psychic,,466,74,48,76,83,81,104,6,False,0.631579,Psychic

In [70]:
#Grouping By Combo Types with Mean agg function
df_top_5_types.groupby('Combo Type').agg('mean')

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,A/D Ratio
Combo Type,,,,,,,,,,
Bug - Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,1.315989
Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,1.164196
Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,1.260091
Water - Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,2.291949